
# ----------------------------
# Namespace (idempotent)
# ----------------------------
apiVersion: v1
kind: Namespace
metadata:
  name: observability
---
# ----------------------------
# Grafana datasource provisioning
# ----------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: observability
data:
  prometheus-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.default.svc.cluster.local:9090
        isDefault: true
        editable: true

# ----------------------------
# Grafana dashboards provider
# ----------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-provider
  namespace: observability
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'edge2cloud'
        orgId: 1
        folder: 'Edge2Cloud'
        type: file
        disableDeletion: false
        editable: true
        allowUiUpdates: false
        options:
          path: /var/lib/grafana/dashboards
          # How Grafana interprets files:
          #  - .json files are dashboards
          #  - .yaml files can also define dashboards; we’re using JSON exports here
        # Optional: update interval if files change at runtime
        # updateIntervalSeconds: 30
---
# ----------------------------
# Grafana dashboards (your exported JSON)
# ----------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: observability
data:
  edge2cloud-dashboard.json: |
    # Paste the full contents of your exported dashboard JSON here.
    # Tip: Ensure the datasource references the name "Prometheus"
    # If the export includes hardcoded datasource UID, replace it, see notes below.
    {
      "id": null,
      "uid": "edge2cloud-main",
      "title": "Edge2Cloud",
      "timezone": "browser",
      "version": 1,
      "panels": [
        // ...
      ],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-6h",
        "to": "now"
      }
      // ...
    }
---
# ----------------------------
# Persistent storage for Grafana
# ----------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: observability
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
# ----------------------------
# Grafana Deployment
# ----------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:10.4.2
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: "admin"
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin"
            - name: GF_PATHS_PROVISIONING
              value: /etc/grafana/provisioning
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: grafana-provisioning-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-provisioning-dashboards
              mountPath: /etc/grafana/provisioning/dashboards
            - name: grafana-dashboards
              mountPath: /var/lib/grafana/dashboards
              readOnly: true
      volumes:

      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-data
        - name: grafana-provisioning-datasources
        #- name: grafana-datasources
          configMap:
            name: grafana-datasources
        - name: grafana-provisioning-dashboards
        #- name: grafana-provisioning
          configMap:
            name: grafana-dashboards-provider
        - name: grafana-dashboards
          configMap:
            name: grafana-dashboards
---
# ----------------------------
# Grafana Service (NodePort 32000)
# ----------------------------
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: observability
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - name: http
      port: 3000
      targetPort: 3000
