FROM python:3.11-slim

WORKDIR /app

# System libs für OpenCV
RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

# Python Dependencies
COPY requirements/edge.txt /requirements/edge.txt
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r /requirements/edge.txt

# App Code
COPY edge /app/edge

# Python Path
ENV PYTHONPATH=/app/edge

# Entry Point
CMD ["python3", "/app/edge/app_edge.py"]



